import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/AuthContext"; 
import "./globals.css";
import Script from "next/dist/client/script";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* 🔥 Puter.js direct uplink */}
        <script 
          src="https://js.puter.com/v2/" 
          data-puter-no-login="true" 
          data-puter-no-desktop="true"
          >
          
        </script>
      </head>
      
      <body>
       
        <AuthProvider>
          {children}
        </AuthProvider>
        
      </body>
    </html>
  );
}

