export default function TermsAndConditionsPage() {
  return (
    <main style={{ padding: "40px", maxWidth: "900px", margin: "auto", gap: "3px" }}>
      <h1>Terms & Conditions</h1>
      <p><strong>Last updated:</strong> 2026</p>

      <p>
        Welcome to Thinkhatch. By accessing or using our website, applications,
        or services, you agree to comply with and be bound by the following
        Terms & Conditions. Please read them carefully before using the platform.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By using Thinkhatch, you confirm that you have read, understood, and
        accepted these terms. If you do not agree with any part of these terms,
        you should discontinue use of the platform.
      </p>

      <h2>2. Platform Purpose</h2>
      <p>
        Thinkhatch provides AI-powered tools for students, professionals,
        creators, startups, and businesses. The platform is designed to assist
        learning, productivity, automation, and decision-making — not to replace
        human judgment or professional advice.
      </p>

      <h2>3. User Responsibilities</h2>
      <ul>
        <li>You agree to use Thinkhatch for lawful and ethical purposes only</li>
        <li>You will not upload illegal, harmful, or sensitive content</li>
        <li>You are responsible for maintaining the confidentiality of your account</li>
        <li>You will not misuse or attempt to disrupt the platform</li>
      </ul>

      <h2>4. AI-Generated Content Disclaimer</h2>
      <p>
        Outputs generated by Thinkhatch are based on artificial intelligence and
        may not always be accurate or complete. Users are responsible for
        verifying results before relying on them for academic, professional, or
        business decisions.
      </p>

      <h2>5. Intellectual Property</h2>
      <p>
        All content, branding, design, and platform architecture belong to
        Thinkhatch or its licensors. Users retain ownership of their uploaded
        content, but grant Thinkhatch limited rights to process it for service
        delivery.
      </p>

      <h2>6. Service Availability</h2>
      <p>
        We strive to keep the platform available at all times, but do not
        guarantee uninterrupted access. Features may be updated, modified, or
        discontinued without prior notice.
      </p>

      <h2>7. Payments & Subscriptions</h2>
      <p>
        Some features may be offered under free or paid plans. Pricing,
        limitations, and terms will be clearly communicated before purchase.
        Payments once made are generally non-refundable unless stated otherwise.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        Thinkhatch shall not be liable for any direct, indirect, incidental, or
        consequential damages arising from use or inability to use the
        platform, including data loss or academic/professional outcomes.
      </p>

      <h2>9. Termination</h2>
      <p>
        We reserve the right to suspend or terminate access to the platform if
        users violate these terms or misuse services.
      </p>

      <h2>10. Changes to Terms</h2>
      <p>
        These terms may be updated from time to time. Continued use of
        Thinkhatch after changes indicates acceptance of the revised terms.
      </p>

      <h2>11. Governing Law</h2>
      <p>
        These Terms & Conditions are governed by and interpreted in accordance
        with the laws of India.
      </p>

      <h2>12. Contact Information</h2>
      <p>
        For any questions regarding these Terms, please contact us at:
        <strong> feedbackform.yt@gmail.com</strong>
      </p>

      <p style={{ marginTop: "40px", fontSize: "14px", opacity: 0.7 }}>
        Thinkhatch is an initiative powered by KDCGC.
      </p>
    </main>
  );
}